### PR TITLE
Retry prunning on error

### LINKED ISSUE #1: Not allowed to prune networks in paralell
When trying to remove networks, these messages might appear in the logs:
`level=error msg="Handler for POST /v1.29/networks/prune returned error: a prune operation is already running"`

### PR DESCRIPTION
**Pull request by bsideup**
Fixes #1

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -14,13 +14,14 @@ import (
...
 	"github.com/docker/docker/client"
+	"gopkg.in/matryer/try.v1"
 )
 
 var port = flag.Int("p", 8080, "Port to bind at")
 
 func main() {
 	flag.Parse()
-	log.Printf("Starting on port %d...", *port)
+	log.Println("Pinging Docker...")
```
Comment (bsideup) [inline main.go:24]: the logging changes are unrelated a bit but a good general improvement

Comment (kiview) [reply main.go:24]: I agree, I think it would be even a good idea to log the actual prune operation as well, potentially with the retry number, just as some telemetry?

File: main.go [hunk 2]
```diff
@@ -132,15 +141,29 @@ TimeoutLoop:
 			}
 		}
 
-		networksPruneReport, err := cli.NetworksPrune(context.Background(), args)
-		for _, networkID := range networksPruneReport.NetworksDeleted {
-			deletedNetworks[networkID] = true
-		}
+		try.Do(func(attempt int) (bool, error) {
```
Comment (kiview) [inline main.go:144]: This is a completely 3rd party library, or?
So basically just applied [this pattern](https://github.com/matryer/try#delay-between-retries), correct?

File: main.go (hunk 1 above)
Comment (bsideup) [reply main.go:24]: Will add 👍
